frontend/controllers/CatalogController.php
<?php
namespace frontend\controllers;

use common\models\Goods;
use common\models\Podrazdel;
use common\models\Podrazdel3lvl;
use common\models\Razdel;
use common\models\UserViewedGoods;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Catalog controller
 */
class CatalogController extends Controller
{
    public function actionCategory($name)
    {
        $model = Razdel::find()->where(['rz_url' => $name])->show()->with(['sections'])->one();
        if($model === null){
            throw new NotFoundHttpException;
        }

        $sectionsHasCharakters = [];
        $childSections = $model['sections'];
        foreach($childSections as $section) {
            if(isset($section['prz_charakters'])) {
                $sectionsHasCharakters[] = $section['prz_id'];
            }
        }

        $categoryRing = Razdel::getRing($model->rz_id);

        $compareIds = $this->getCompareIds();

        $positions = Goods::find()
            ->addSelect(Yii::$app->params['good_fields'])
            ->joinWith([
                'sectionGoods' => function ($query) use ($childSections) { /* @var $query ActiveQuery */
                    $query->andWhere([
                        'cat_id' => array_keys($childSections)
                    ]);
                }
            ])
            ->with(['manufacter', 'unit'])
            ->show()
            ->noDeleted()
            ->indexBy('ct_id')
            ->orderBy(['ct_count_index' => SORT_DESC]);

        $dataProvider = new ActiveDataProvider([
            'query' => $positions,
            'pagination' => [
                'pageSize' => Goods::getPageSize(),
                'totalCount' => $positions->count(),
                'pageSizeParam' => 'psize',
            ],
            'sort' => [
                'enableMultiSort' => true,
                'attributes' => [
                    'price' => [
                        'asc' => ['ct_price' => SORT_ASC],
                        'desc' => ['ct_price' => SORT_DESC],
                        'label' => 'Цене',
                    ],
                    'name' => [
                        'asc' => ['ct_name' => SORT_ASC],
                        'desc' => ['ct_name' => SORT_DESC],
                        'label' => 'Названию',
                    ],
                    'art' => [
                        'asc' => ['ct_newart' => SORT_ASC],
                        'desc' => ['ct_newart' => SORT_DESC],
                        'label' => 'Артикулу',
                    ],
                ],
            ],
        ]);

        return $this->render('category', [
            'model' => $model,
            'compareIds' => $compareIds,
            'dataProvider' => $dataProvider,
            'sectionsHasCharakters' => $sectionsHasCharakters,
            'categoryRing' => $categoryRing,
        ]);
    }

    public function actionSection($name)
    {
        $model = Podrazdel::find()->where(['prz_url' => $name])
            ->with(['subsections', 'category', 'seoTags', 'seo3lvl'])
            ->show()->one();
        if($model === null){
            throw new NotFoundHttpException;
        }

        $otherSections = Podrazdel::find()->select(['prz_name', 'prz_url', 'prz_pic'])
            ->where(['prz_rz_id' => $model['category']['rz_id']])->show()->asArray()->all();

        $compareIds = $this->getCompareIds();

        $sectionId = $model->prz_id;
        $positions = Goods::find()
                ->addSelect(Yii::$app->params['good_fields'])
                ->joinWith([
                    'sectionGoods' => function ($query) use ($sectionId) { /* @var $query ActiveQuery */
                        $query->andWhere([
                            'cat_id' => $sectionId
                        ]);
                    }
                ])
                ->with(['manufacter', 'unit'])
                ->show()
                ->noDeleted()
                ->sectionFiltersHandle($sectionId)
                ->indexBy('ct_id')
                ->orderBy(['ct_count_index' => SORT_DESC]);

        $dataProvider = new ActiveDataProvider([
            'query' => $positions,
            'pagination' => [
                'pageSize' => Goods::getPageSize(),
                'totalCount' => $positions->count(),
                'pageSizeParam' => 'psize',
            ],
            'sort' => [
                'enableMultiSort' => true,
                'attributes' => [
                    'price' => [
                        'asc' => ['ct_price' => SORT_ASC],
                        'desc' => ['ct_price' => SORT_DESC],
                        'label' => 'Цене',
                    ],
                    'name' => [
                        'asc' => ['ct_name' => SORT_ASC],
                        'desc' => ['ct_name' => SORT_DESC],
                        'label' => 'Названию',
                    ],
                    'art' => [
                        'asc' => ['ct_newart' => SORT_ASC],
                        'desc' => ['ct_newart' => SORT_DESC],
                        'label' => 'Артикулу',
                    ],
                ],
            ],
        ]);

        return $this->render('section', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'otherSections' => $otherSections,
            'compareIds' => $compareIds
        ]);
    }

    public function actionSubsection($name)
    {
        $model = Podrazdel3lvl::find()->where(['pprz_url' => $name])
            ->with(['section.category', 'seoTags', 'seo4lvl'])
            ->show()->one();
        if($model === null){
            throw new NotFoundHttpException;
        }

        $otherSubsections = Podrazdel3lvl::find()->select(['pprz_name', 'pprz_url', 'pprz_pic'])
            ->where(['pprz_prz_id' => $model['section']['prz_id']])->show()->asArray()->all();

        $compareIds = $this->getCompareIds();
        $subsectionId = $model->pprz_id;
        $positions = Goods::find()
            ->addSelect(Yii::$app->params['good_fields'])
            ->joinWith([
                'subsectionGoods' => function ($query) use ($subsectionId) { /* @var $query ActiveQuery */
                    $query->andWhere([
                        'subcat_id' => $subsectionId
                    ]);
                }
            ])
            ->with(['manufacter', 'unit'])
            ->show()
            ->noDeleted()
            ->subsectionFiltersHandle($subsectionId)
            ->indexBy('ct_id')
            ->orderBy('ct_count_index DESC');

        $dataProvider = new ActiveDataProvider([
            'query' => $positions,
            'pagination' => [
                'pageSize' => Goods::getPageSize(),
                'totalCount' => $positions->count(),
                'pageSizeParam' => 'psize',
            ],
            'sort' => [
                'enableMultiSort' => true,
                'attributes' => [
                    'price' => [
                        'asc' => ['ct_price' => SORT_ASC],
                        'desc' => ['ct_price' => SORT_DESC],
                        'label' => 'Цене',
                    ],
                    'name' => [
                        'asc' => ['ct_name' => SORT_ASC],
                        'desc' => ['ct_name' => SORT_DESC],
                        'label' => 'Названию',
                    ],
                    'art' => [
                        'asc' => ['ct_newart' => SORT_ASC],
                        'desc' => ['ct_newart' => SORT_DESC],
                        'label' => 'Артикулу',
                    ],
                ],
            ],
        ]);

        return $this->render('subsection', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'otherSubections' => $otherSubsections,
            'compareIds' => $compareIds
        ]);
    }

    public function actionItem($id)
    {
        /* @var $item Goods */
        $item = Goods::find()->where(['ct_url' => $id])->with([
                'reviews',
                'section',
                'subsection',
                'morePhotos',
                'unit',
                'manufacter'
            ])->one();
        if($item === null) {
            throw new NotFoundHttpException;
        }

        $this->setViewed($item->ct_id);
        $compareIds = $this->getCompareIds();
        $reviews = $item->reviews;
        $section = $item->section;
        $subsection = $item->subsection;
        $morePhotos = $item->morePhotos;
        $unit = $item->unit['name'];
        $manufacter = $item->manufacter;
        $tabs = $item->getGoodsForTabs();

        return $this->render('item', [
            'item' => $item,
            'unit' => $unit,
            'tabs' => $tabs,
            'reviews' => $reviews,
            'section' => $section,
            'subsection' => $subsection,
            'compareIds' => $compareIds,
            'morePhotos' => $morePhotos,
            'manufacter' => $manufacter,
        ]);
    }

    protected function setViewed($id)
    {
        if(Yii::$app->user->isGuest) {
            $session = Yii::$app->session;
            if($session->has('viewed_goods')) {
                $goods = $session->get('viewed_goods');
                if(!in_array($id, $goods)) {
                    $goods[] = $id;
                    $session->set('viewed_goods', $goods);
                }
            } else {
                $session->set('viewed_goods', [$id]);
            }
        } else {
            $findGood = UserViewedGoods::find()->where([
                'user_id' => Yii::$app->user->id,
                'good_id' => $id,
            ])->one();
            if(is_null($findGood)) {
                $model = new UserViewedGoods();
                $model->user_id = Yii::$app->user->id;
                $model->good_id = $id;
                $model->save(false);
            }
        }

frontend/views/catalog/_itemMorePhotos.php
<?php
/* @var $this yii\web\View */
/* @var $name string */
/* @var $photos [] */

$i = 0;
use yii\helpers\Html;
?>

<?php if(sizeof($photos) > 0) { ?>
    <div class="small-3 columns">
        <div class="thumbnails">
            <?php foreach($photos as $photo) { ?>
                <?php if($i <= 3) { ?>
                    <noindex>
                        <?= Html::a(
                            Html::img('http://www.gipostroy.ru/pdir/more/' . $photo['photo'], [
                                'alt' => $name,
                                'title' => $name,
                                'style' => 'width:100px;height:90px;margin-bottom:8px;'
                            ]),
                            'http://www.gipostroy.ru/pdir/more/' . $photo['photo'],
                            [
                                'class' => 'fancybox',
                                'rel' => 'group',
                            ]
                        ) ?>
                    </noindex>
                <?php } ?>
                <?php $i++; ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>

frontend/views/catalog/_itemSchema.php
<?php
/* @var $price integer */
/* @var $name string */
/* @var $pic string */
/* @var $text string */
/* @var $reviews [] */

$allReviews = 0;
$totalRate = 0;
foreach($reviews as $review) {
    $allReviews++;
    $totalRate += $review['rate'];
}
?>

<?php if(sizeof($reviews) > 0) { ?>
    <div itemscope itemtype="http://schema.org/Product">
        <span itemprop="name"><?= $name ?></span>
        <img src=<?= $pic ?>" alt="<?= $name ?>" />
        <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
            Оценка <span itemprop="ratingValue"><?= round($totalRate / $allReviews, 1, PHP_ROUND_HALF_UP) ?></span>/5
            Основана <span itemprop="reviewCount"><?= $allReviews ?></span> отзывах пользователей
        </div>
        <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <span itemprop="priceCurrency" content="RUB">RUB</span>
            <span itemprop="price" content="<?= $price ?>"><?= $price ?></span>
        </div>
        <span itemprop="description">
            <?= $text ?>
        </span>
        <?php foreach($reviews as $r) { ?>
            <div itemprop="review" itemscope itemtype="http://schema.org/Review">
                <span itemprop="name"><?= $r['email'] ?></span> -
                by <span itemprop="author"><?= $r['name'] ?></span>,
                <meta itemprop="datePublished" content="<?= $r['date_review'] ?>"><?= $r['date_review'] ?>
                <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                    <meta itemprop="worstRating" content = "1">
                    <span itemprop="ratingValue"><?= $r['rate'] ?></span>/
                    <span itemprop="bestRating">5</span>
                </div>
                <span itemprop="description">
                    <?= $r['text'] ?>
                </span>
            </div>
        <?php } ?>
    </div>
<?php } ?>

frontend/views/catalog/category.php
<?php
/* @var $this yii\web\View */
/* @var $model Razdel */
/* @var $compareIds array() */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $categoryRing array() */
/* @var $sectionsHasCharakters array() */
use common\models\Goods;
use common\models\Razdel;
use yii\helpers\Html;
use frontend\components\widgets\LeftCatalogWidget;
use frontend\components\widgets\SearchBlockWidget;
use yii\widgets\LinkPager;

$this->title = $model->getTitle();
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->getDescription(),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->getKeywords(),
]);

$this->params['breadcrumbs'][] = Html::a($model->rz_name, ['catalog/category', 'name' => $model->rz_url]);
?>

<section id="main">
    <div class="wrap">
        <aside>
            <?= LeftCatalogWidget::widget() ?>
        </aside>
        <div id="content" class="container">
            <?= SearchBlockWidget::widget(); ?>

            <div class="breadcrumb">
                <?= yii\widgets\Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'encodeLabels' => false,
                    'options' => [
                        'class' => 'nav'
                    ],
                ]) ?>
            </div>

            <div class="page catalog">

                <div class="categories">
                    <?php foreach($model['sections'] as $section) { ?>
                    <div class="categoryImages">
                        <?php if(in_array($_SERVER['SERVER_NAME'],array('develop.gipostroy.ru', 'gipo.loc', 'gipo2yii.loc', 'yiishop.loc'))) {
                            $src = 'http://www.gipostroy.ru/img/catalog/' . $section['prz_pic'];
                        } elseif(file_exists($_SERVER['DOCUMENT_ROOT'].'/img/catalog/' . $section['prz_pic'])) {
                            $src = '/img/catalog/' . $section['prz_pic'];
                        } else {
                            $src = '/images/nophoto.jpg';
                        } ?>

                        <?= Html::a(
                            Html::img($src, ['alt' => $section['prz_name'], 'title' => $section['prz_name']]) . '<span>' . $section['prz_name'] . '</span>',
                            ['catalog/section', 'name' => $section['prz_url']]
                        ) ?>
                    </div>
                    <?php } ?>
                </div>

                <header>
                    <h2 class="catHeader">
                        <?= $model->getHeader() ?>
                    </h2>
                </header>

                <div class="sort">
                    <div class="row">
                        <div class="small-6 columns">
                            Сортировать по
                            <?= $dataProvider->sort->link('price') ?>
                            <?= $dataProvider->sort->link('name') ?>
                            <?= $dataProvider->sort->link('art') ?>
                        </div>
                        <div class="small-6 columns text-right view-options">
                            Показать в виде: <a href="#" class="changeDisplayGoods list<?= (Goods::getDisplayGoods()=='list') ? ' active' : '' ?>"></a><a href="#" class="changeDisplayGoods plate<?= (Goods::getDisplayGoods()=='list') ? '' : ' active' ?>"></a>
                        </div>
                    </div>
                </div>

                <?php if($dataProvider->totalCount > 24) { ?>
                    <div class="listing-options row">
                        <div class="small-6 small-offset-3 columns text-center pagination">
                            <?= LinkPager::widget([
                                'pagination' => $dataProvider->pagination,
                                'nextPageLabel' => 'Следующая',
                                'prevPageLabel' => 'Предыдущая',
                                'maxButtonCount' => 9,
                            ]) ?>
                        </div>
                        <div class="small-2 columns show-by text-right">
                            <label>
                                Показать по:
                                <select id="pSize" class="chosen-select show-by-select" name="psize">
                                    <option value="24" <?= (Goods::getPageSize() == 24) ? 'selected' : '' ?>>24</option>
                                    <option value="48" <?= (Goods::getPageSize() == 48) ? 'selected' : '' ?>>48</option>
                                    <option value="72" <?= (Goods::getPageSize() == 72) ? 'selected' : '' ?>>72</option>
                                    <option value="96" <?= (Goods::getPageSize() == 96) ? 'selected' : '' ?>>96</option>
                                    <option value="all" <?= (Goods::getPageSize() == 'all') ? 'selected' : '' ?>>Все</option>
                                </select>
                            </label>
                        </div>
                    </div>
                <?php } ?>

                <div class="result">
                    <ul class="<?= Goods::getDisplayGoods() ?>">
                        <?php /* @var $good Goods */ ?>
                        <?php foreach($dataProvider->getModels() as $good) { ?>
                            <li>
                                <div class="product">
                                    <?php if($good->ct_sale == 1) { ?>
                                        <div class="good-discount"></div>
                                    <?php } elseif($good->ct_hit == 1) { ?>
                                        <div class="good-hit"></div>
                                    <?php } elseif($good->isNewGood()) { ?>
                                        <div class="good-new"></div>
                                    <?php } ?>
                                    <div class="product-image">
                                        <?= Html::a(
                                            Html::img($good->getImageSrc(), [
                                                'alt' => $good['ct_name'],
                                                'title' => $good['ct_name'],
                                                'class' => 'image',
                                            ]),
                                            [
                                                'catalog/item',
                                                'id' => $good['ct_url']
                                            ],
                                            [
                                                'title' => $good['ct_name'],
                                            ]
                                        ) ?>
                                    </div>
                                    <div class="product-description">
                                        <?= Html::a(
                                            $good->ct_name,
                                            ['catalog/item', 'id' => $good->ct_url],
                                            ['title' => $good->ct_name]
                                        ) ?>
                                        <table class="params">
                                            <tr>
                                                <td>Артикул</td>
                                                <td><?= $good->ct_newart ?></td>
                                            </tr>
                                            <?php if(!empty($good['manufacter']['mn_name'])) { ?>
                                                <tr>
                                                    <td>Производитель</td>
                                                    <td><?= $good['manufacter']['mn_name'] ?></td>
                                                </tr>
                                            <?php }?>
                                            <?php if(!empty($good['manufacter']['mn_country'])) { ?>
                                                <tr>
                                                    <td>Страна</td>
                                                    <td><?= $good['manufacter']['mn_country'] ?></td>
                                                </tr>
                                            <?php }?>
                                        </table>
                                    </div>
                                    <footer>
                                        <div class="available">
                                            <?= $good->getGoodBalance($good['unit']['name']) ?>
                                        </div>
                                        <div class="price">
                                            <?= $good->getGoodPriceBlock() ?>
                                        </div>
                                        <div class="buttons">
                                            <?= $good->getGoodBasketButton() ?>
                                        </div>
                                        <div class="shipping">
                                            <?= $good->getGoodShipping(); ?>
                                        </div>
                                        <?= $good->getGoodsCompareBlock($sectionsHasCharakters, $compareIds) ?>
                                    </footer>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>
                </div>

                <?php if($dataProvider->totalCount > 24) { ?>
                    <div class="listing-options row">
                        <div class="small-6 small-offset-3 columns text-center pagination">
                            <?= LinkPager::widget([
                                'pagination' => $dataProvider->pagination,
                                'nextPageLabel' => 'Следующая',
                                'prevPageLabel' => 'Предыдущая',
                                'maxButtonCount' => 9,
                            ]) ?>
                        </div>
                        <div class="small-2 columns show-by text-right">
                            <label>
                                Показать по:
                                <select id="pSize" class="chosen-select show-by-select" name="psize">
                                    <option value="24" <?= (Goods::getPageSize() == 24) ? 'selected' : '' ?>>24</option>
                                    <option value="48" <?= (Goods::getPageSize() == 48) ? 'selected' : '' ?>>48</option>
                                    <option value="72" <?= (Goods::getPageSize() == 72) ? 'selected' : '' ?>>72</option>
                                    <option value="96" <?= (Goods::getPageSize() == 96) ? 'selected' : '' ?>>96</option>
                                    <option value="all" <?= (Goods::getPageSize() == 'all') ? 'selected' : '' ?>>Все</option>
                                </select>
                            </label>
                        </div>
                    </div>
                <?php } ?>

                <div class="category-rings">
                    <?= Html::a(
                        '<<< ' . $categoryRing['prev']['rz_name'],
                        ['catalog/category', 'name' => $categoryRing['prev']['rz_url']],
                        [
                            'class' => 'prev'
                        ]
                    ) ?>
                    <?= Html::a(
                        $categoryRing['next']['rz_name'] . ' >>>',
                        ['catalog/category', 'name' => $categoryRing['next']['rz_url']],
                        [
                            'class' => 'next'
                        ]
                    ) ?>
                </div>
                <div class="clear"></div>

                <div class="immersed" id="non-selectable">
                    <div class="description" style="text-align:justify">
                        <?php if(Yii::$app->request->get('page') <= 1) { ?>
                            <?= $model->getText() ?>
                        <?php } ?>
                        <p>
                            Информация об условиях и способах оплаты товаров из каталога “<?= $model->rz_name ?>” доступна на
                            странице “<noindex><?= Html::a('Оплата', ['page/article', 'name' => 'delivery'], ['rel' => 'nofollow']) ?></noindex>”.
                        </p>
                        <p>
                            О стоимости. сроках и условиях доставки по Москве (в пределах МКАД) и в
                            регионы России читайте на странице “<noindex><?= Html::a('Доставка', ['page/article', 'name' => 'delivery'], ['rel' => 'nofollow']) ?></noindex>”.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>