backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\GoodCat;
use common\models\Goods;
use common\models\GoodSubcat;
use common\models\Manufacter;
use common\models\Razdel;
use common\models\RRCache;
use common\models\Sitepages;
use Yii;
use yii\filters\PageCache;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => 'yii\web\ErrorAction',
        ];
    }

    public function actionIndex()
    {
        $goodsIds = RRCache::getItemsToMain(4);
        $goodsFromDb = Goods::getDb()->cache(function($db) use ($goodsIds){
            return Goods::find()->where(['ct_id' => $goodsIds])->indexBy('ct_id')->all();
        }, 600);
        $goods = [];
        foreach ($goodsIds as $k => $v) {
            $goods[$k] = $goodsFromDb[$v];
        }
        $razdelImages = Razdel::getDb()->cache(function($db){
            return Razdel::find()->show()->notSale()->notNY()->asArray()->orderBy('rz_sorti ASC')->all();
        }, 100);
        $title = 'Гипострой.ру - интернет-магазин стройматериалов в Москве и области. Гипермаркет
            строительных материалов';
        $description = 'Гипострой.ру - интернет-магазин строительных материалов. ☎ +7 (495) 545-44-547 Стройматериалы по
            доступной цене! Продажа стройматериалов с доставкой по Москве и области!';
        $keywords = '';
        return $this->render('index', [
            'title' => $title,
            'keywords' => $keywords,
            'description' => $description,
            'goods' => $goods,
            'razdelImages' => $razdelImages,
        ]);
    }

    public function actionArticle($name)
    {
        $oldPages = ['help', 'grafik-raboty', 'legal-information'];
        if(in_array($name, $oldPages)) {
            $this->redirect(['site/article', 'name' => 'about'], 301);
        }

        $model = Sitepages::getDb()->cache(function($db) use ($name){
            return Sitepages::findOne(['sp_url' => $name]);
        }, 1000);

        if($model === null) {
            throw new NotFoundHttpException;
        }

        if($name == 'delivery') {
            return $this->render('delivery', [
                'model' => $model,
            ]);
        } elseif($name == 'contacts') {
            return $this->render('contacts', [
                'model' => $model,
            ]);
        } else {
            return $this->render('default', [
                'model' => $model,
            ]);
        }
    }

    public function actionTop()
    {
        $rrGoods = RRCache::getItemsToMain();
        $positions = Goods::getDb()->cache(function($db) use ($rrGoods){
            return Goods::find()
                ->addSelect(Yii::$app->params['good_fields'])
                ->with(['manufacter', 'unit'])
                ->show()
                ->where(['in', 'ct_id', $rrGoods])
                ->noDeleted()
                ->indexBy('ct_id')
                ->all();
        }, 1000);
        foreach($rrGoods as $k => $rrId) {
            if(isset($positions[$rrId])) {
                $rrGoods[$k] = $positions[$rrId];
            } else {
                unset($rrGoods[$k]);
            }
        }

        $title = 'Интернет-гипермаркет Гипострой — лидер продаж стройматериалов в Москве.';
        $description = 'Лидеры продаж в  интернет-гипермаркете стройматериалов Гипострой. Продажа популярных
            строительных материалов по доступным ценам с доставкой по Москве и области. Заказывать у нас  просто и выгодно!';
        $keywords = '';

        return $this->render('top', [
            'title' => $title,
            'description' => $description,
            'keywords' => $keywords,
            'positions' => $rrGoods,
        ]);
    }

    public function actionKompleks()
    {
        $title = 'Комплектация и снабжение строительных объектов материалами, Москва и область. Оптовая продажа, комплексная поставка стройматериалов';
        $description = 'Комплексное снабжение и комплектация строительных объектов стройматериалами в Москве. Оптовая продажа и поставка строительных материалов,
            сантехники  по лучшим ценам в компании Гипострой.';
        $keywords = '';

        return $this->render('kompleks', [
            'title' => $title,
            'description' => $description,
            'keywords' => $keywords,
        ]);
    }

    public function actionMap()
    {
        $map = Razdel::getDb()->cache(function($db){
            return Razdel::find()
                ->with(['sections.subsections'])
                ->show()
                ->orderBy([
                    'rz_sorti' => SORT_ASC
                ])
                ->asArray()
                ->all();
        }, 1000);
        $staticPages = Sitepages::getDb()->cache(function($db){
            return Sitepages::find()->show()->orderBy(['sp_sorti' => SORT_ASC])->asArray()->all();
        }, 1000);
        $title = 'Карта сайта интернет-гипермаркета Гипострой.ру';
        $description = 'Карта сайта интернет-гипермаркета Гипострой.ру. Заказывайте качественные строительные материалы у нас! Недорого!';
        $keywords = '';

        return $this->render('map', [
            'title' => $title,
            'description' => $description,
            'keywords' => $keywords,
            'map' => $map,
            'staticPages' => $staticPages,
        ]);
    }

    public function actionProizvoditeli()
    {
        $manufacters = Manufacter::getDb()->cache(function($db){
            return Manufacter::find()
                ->addSelect(['mn_name', 'mn_url', 'LEFT(mn_name, 1) as alphabet'])
                ->show()
                ->orderBy([
                    'mn_name' => SORT_ASC
                ])
                ->asArray()
                ->all();
        }, 1000);
        $manufactersArray = [];
        foreach($manufacters as $manufacter) {
            $manufactersArray[$manufacter['alphabet']][] = $manufacter;
        }

        $enAlphabet = range('A','Z');
        $ruAlphabet = array('А','Б','В','Г','Д','Е','Ё','Ж','З','И','К','Л','М','Н','О','П','Р','С','Т','У',
            'Ф','Х','Ц','Ч','Щ','Ш','Ь','Ы','Ъ','Э','Ю','Я');

        $title = 'Производители';
        $description = '';
        $keywords = '';

        return $this->render('manufacters', [
            'title' => $title,
            'description' => $description,
            'keywords' => $keywords,
            'manufacters' => $manufactersArray,
            'enAlphabet' => $enAlphabet,
            'ruAlphabet' => $ruAlphabet,
        ]);
    }

    /**
     * Показываем информацию о выбранном производителе
     * @param $name
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionShow($name)
    {
        $model = Manufacter::find()
            ->where(['mn_url' => $name])
            ->show()
            ->one();
        if($model === null) {
            throw new NotFoundHttpException;
        }

        $subsections = GoodSubcat::find()
            ->select('subcat_id', 'distinct')
            ->where(['manufacter_id' => $model['mn_id']])
            ->with(['subsection.section'])
            ->asArray()
            ->all();

        $catsArray = [];
        foreach($subsections as $subsection) {
            if(!empty($subsection['subsection']['pprz_prz_id'])) {
                $section = $subsection['subsection']['section'];
                if(!isset($catsArray[$section['prz_id']]['subsections'])) {
                    $catsArray[$section['prz_id']] = $section;
                    $catsArray[$section['prz_id']]['subsections'] = [];
                }
                $catsArray[$section['prz_id']]['subsections'][] = $subsection;
            }
        }

        $lvl2 = GoodCat::find()
            ->select('cat_id', 'distinct')
            ->where(['manufacter_id' => $model['mn_id']])
            ->with(['section'])
            ->indexBy('cat_id')
            ->asArray()
            ->all();
        foreach($lvl2 as $key => $value) {
            if(isset($catsArray[$value['cat_id']])) {
                unset($lvl2[$key]);
            }
        }

        return $this->render('manufacter', [
            'model' => $model,
            'sections' => $catsArray,
            'lvl2' => $lvl2,
        ]);
    }
}

frontend/views/site/default.php
<?php
/* @var $this yii\web\View */
/* @var $model Sitepages */
use common\models\Sitepages;
use frontend\components\widgets\LeftCatalogWidget;
use frontend\components\widgets\SearchBlockWidget;
use yii\helpers\Html;

$this->title = $model->sp_title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->sp_description,
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->sp_keywords,
]);

$this->params['breadcrumbs'][] = Html::a($model->sp_name, ['site/article', 'name' => $model->sp_url]);
?>

<section id="main">
    <div class="wrap">
        <aside>
            <?= LeftCatalogWidget::widget() ?>
        </aside>
        <div id="content" class="container">
            <?= SearchBlockWidget::widget(); ?>

            <div class="breadcrumb">
                <?= yii\widgets\Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'encodeLabels' => false,
                    'options' => [
                        'class' => 'nav'
                    ],
                ]) ?>
            </div>

            <?=$model['sp_text']?>
        </div>
    </div>
</section>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */
/* @var $title string */
/* @var $description string */
/* @var $keywords string */
/* @var $goods array() */
/* @var $razdelImages array() */
use common\models\Goods;
use yii\helpers\Html;
use frontend\components\widgets\LeftCatalogWidget;
use frontend\components\widgets\SearchBlockWidget;
\frontend\assets\ResponsiveSlidesAsset::register($this);

$this->title = $title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $description
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $keywords
]);
$this->registerJs("
    $('#content .rslides').responsiveSlides({
        pager: true
    });
");
?>

<section id="main">
    <div class="wrap">
        <aside>
            <?= LeftCatalogWidget::widget() ?>
        </aside>
        <div id="content" class="container">
            <?= SearchBlockWidget::widget(); ?>

            <div class="banner">
                <ul class="rslides">
                    <li>
                        <?= Html::a(Html::img('/images/banner/banner_1.jpg'), ['catalog/section', 'name' => 'smesiteli']) ?>
                    </li>
                    <li>
                        <?= Html::a(Html::img('/images/banner/banner_2.jpg'), ['catalog/section', 'name' => 'suhie-smesi']) ?>
                    </li>
                    <li>
                        <?= Html::a(Html::img('/images/banner/banner_3.jpg'), ['catalog/section', 'name' => 'osveschenie']) ?>
                    </li>
                </ul>
            </div>

            <div class="page home with_shadow">

                <div class="lead row">
                    <header class="small-12 columns">
                        <span class="myCustomHeader">Лидеры продаж</span>
                    </header>
                    <div class="products row">
                        <?php /* @var $good Goods */ ?>
                        <?php foreach($goods as $good) { ?>
                            <div class="small-3 columns">
                                <div class="product" style="height:295px;">
                                    <?php if($good->ct_sale == 1) { ?>
                                        <div class="good-discount"></div>
                                    <?php } elseif($good->ct_hit == 1) { ?>
                                        <div class="good-hit"></div>
                                    <?php } elseif($good->isNewGood()) { ?>
                                        <div class="good-new"></div>
                                    <?php } ?>
                                    <div class="widget-product">
                                        <?= Html::a(
                                            Html::img($good->getImageSrc(), ['alt' => $good->ct_name, 'title' => $good->ct_name, 'style' => 'height:212px;']),
                                            [
                                                'catalog/item',
                                                'id' => $good->ct_url,
                                            ],
                                            [
                                                'title' => $good->ct_name,
                                                'onmousedown' => "try { rrApi.recomMouseDown('" . $good->ct_id . "', 'ItemsToMain') } catch (e) {}"
                                            ]
                                        ) ?>
                                    </div>
                                    <div style="clear:both;"></div>
                                    <div class="desq text-center">
                                        <?= Html::a($good->ct_name, ['catalog/item', 'id' => $good->ct_url], [
                                            'title' => $good->ct_name,
                                            'onmousedown' => "try { rrApi.recomMouseDown('" . $good->ct_id . "', 'ItemsToMain') } catch (e) {}"
                                        ]) ?>
                                    </div>
                                    <footer>
                                        <div class="price">
                                            <?= $good->getGoodPriceInteger() ?>
                                        </div>
                                            <?= $good->getGoodBasketButton() ?>
                                    </footer>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <footer class="small-12 columns text-right" style="margin-top: 10px;">
                        <?= Html::a('Показать все', 'top-sales') ?>
                    </footer>
                </div>
                <div class="immersed">
                    <div class="categories text-center row">
                        <?php foreach($razdelImages as $razdel) { ?>
                            <div class="category small-3 columns end">
                                <?= Html::a(
                                    Html::img('/images/categories/' . $razdel['rz_pic'], [
                                        'alt' => $razdel['rz_name'],
                                        'title' => $razdel['rz_name'],
                                    ]) . '<span>' . $razdel['rz_name'] . '</span>',
                                    [
                                        'catalog/category',
                                        'name' => $razdel['rz_url'],
                                    ]
                                ) ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <div class="company row">
                    <div class="logo small-4 columns text-center">
                        <?= Html::img('/images/logo_big.png', [
                            'alt' => 'Интернет-магазин стройматериалов «Гипострой.ру»',
                            'title' => 'Интернет-магазин стройматериалов «Гипострой.ру»',
                        ]) ?>
                    </div>
                    <div class="small-7 columns end">
                        <header>
                            <h1>Интернет магазин строительных материалов Гипострой.ру</h1>
                        </header>
                        <p>
                            Мы хорошо знаем, что такое ремонт и строительство. Мы знаем, как сложно представив облик
                            будущего жилища, воплотить в жизнь все мечты. Чтобы сложное стало легким мы разработали
                            удобный каталог, системы поиска товаров и создали качественное описание к каждой позиции
                            нашего интернет-гипермаркета. Теперь вам проще искать, проще выбирать и проще покупать.
                            Покупать все необходимое в одном месте!
                        </p>
                    </div>
                </div>
                <div class="benefits row">
                    <header class="small-12 columns text-center">
                        <h3>Наши преимущества</h3>
                    </header>
                    <div class="small-6 columns">
                        <figure>
                            <?= Html::img('/images/labels/assortment.png', [
                                'alt' => 'Большой ассортимент стройматериалов',
                                'title' => 'Большой ассортимент стройматериалов',
                            ]) ?>
                            <figcaption>
                                <h4>Большой ассортимент</h4>
                                <p>
                                    Мы собрали в одном интернет-магазине всех известных производителей товаров для
                                    строительства и ремонта. В настоящий момент на сайте более 50000 товаров и их
                                    ассортимент постоянно растет.
                                </p>
                            </figcaption>
                        </figure>
                    </div>
                    <div class="small-6 columns">
                        <figure>
                            <?= Html::img('/images/labels/price.png', [
                                'alt' => 'Самая низкая стоимость стройматериалов в Москве',
                                'title' => 'Самая низкая стоимость стройматериалов в Москве',
                            ]) ?>
                            <figcaption>
                                <h4>Низкая стоимость</h4>
                                <p>
                                    Наши цены способны порадовать даже самого экономного покупателя. Они регулярно
                                    корректируются, чтобы оправдать ваши ожидания.
                                </p>
                            </figcaption>
                        </figure>
                    </div>
                    <div class="small-6 columns">
                        <figure>
                            <?= Html::img('/images/labels/delivery.png', [
                                'alt' => 'Быстрая доставка стройматериалов по Москве и области',
                                'title' => 'Быстрая доставка стройматериалов по Москве и области',
                            ]) ?>
                            <figcaption>
                                <h4>Быстрая доставка</h4>
                                <p>
                                    Мы быстро доставим ваши покупки вне зависимости от адреса доставки, объема
                                    или массы заказа. С нами ремонт - это быстро.
                                </p>
                            </figcaption>
                        </figure>
                    </div>
                    <div class="small-6 columns">
                        <figure>
                            <?= Html::img('/images/labels/consult.png', [
                                'alt' => 'Квалифицированные консультации в интернет-магазине «Гипострой.ру»',
                                'title' => 'Квалифицированные консультации в интернет-магазине «Гипострой.ру»',
                            ]) ?>
                            <figcaption>
                                <h4>Квалифицированные консультации</h4>
                                <p>
                                    Наши менеджеры - профессионалы своего дела. Они всегда окажут квалифицированную
                                    помощь в выборе товара и ответят на все ваши вопросы.
                                </p>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/site/manufacter.php
<?php
/* @var $this yii\web\View */
/* @var $model Manufacter */
/* @var $sections array() */
/* @var $lvl2 array() */

use common\models\Manufacter;
use yii\helpers\Html;
use frontend\components\widgets\LeftCatalogWidget;
use frontend\components\widgets\SearchBlockWidget;

$this->title = $model->getManufactersPageTitle();
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->getManufactersPageDescription()
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->getManufactersPageKeywords()
]);

$this->params['breadcrumbs'][] = Html::a('Производители', ['site/proizvoditeli']);
$this->params['breadcrumbs'][] = Html::a($model->mn_name, ['site/show', 'name' => $model->mn_url]);
?>

<section id="main">
    <div class="wrap">
        <aside>
            <?= LeftCatalogWidget::widget() ?>
        </aside>
        <div id="content" class="container">
            <?= SearchBlockWidget::widget(); ?>

            <div class="breadcrumb">
                <?= yii\widgets\Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'encodeLabels' => false,
                    'options' => [
                        'class' => 'nav'
                    ],
                ]) ?>
            </div>

            <div class="page text-left">
                <header>
                    <?= $model->getManufactersPageHeader() ?>
                </header>

                <?php if(!empty($sections) && !empty($lvl2)) { ?>
                    <div class="manufacter_cats">
                        <header>
                            <h2>Категории, в которых представлен данный производитель</h2>
                        </header>
                        <?php if(!empty($sections)) { ?>
                            <?php foreach($sections as $section) { ?>
                                <div>
                                    <?= Html::a(
                                        $section['prz_name'],
                                        ['catalogmanufacter/section', 'name' => $section['prz_url'], 'manuf' => $model->mn_url],
                                        [
                                            'class' => 'mnCat'
                                        ]
                                    ) ?>
                                    <?php if(!empty($section['subsections'])) { ?>
                                        <br/>
                                        <?php foreach($section['subsections'] as $subsection) { ?>
                                            <?= Html::a(
                                                $subsection['subsection']['pprz_name'],
                                                ['catalogmanufacter/subsection', 'name' => $subsection['subsection']['pprz_url'], 'manuf' => $model->mn_url],
                                                [
                                                    'class' => 'mnSubcat',
                                                ]
                                            ) ?>
                                            <br/>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                        <?php if(!empty($lvl2)) { ?>
                            <?php foreach($lvl2 as $section) { ?>
                                <div>
                                    <?= Html::a(
                                        $section['section']['prz_name'],
                                        ['catalogmanufacter/section', 'name' => $section['section']['prz_url'], 'manuf' => $model->mn_url],
                                        [
                                            'class' => 'mnCat'
                                        ]
                                    ) ?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                <?php } ?>

                <div class="manufacter_desc" id="non-selectable">
                    <?= Html::img($model->getImageSrc(), [
                        'class' => 'image manufacter-image',
                        'alt' => $model->mn_name,
                        'title' => $model->mn_name,
                    ]) ?>
                    <?= $model->getManufactersPageText() ?>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/site/manufacters.php
<?php
/* @var $this yii\web\View */
/* @var $title string */
/* @var $description string */
/* @var $keywords string */
/* @var $manufacters array() */
/* @var $enAlphabet array() */
/* @var $ruAlphabet array() */

use yii\helpers\Html;
use frontend\components\widgets\LeftCatalogWidget;
use frontend\components\widgets\SearchBlockWidget;

$this->title = $title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $description
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $keywords
]);

$this->params['breadcrumbs'][] = Html::a('Производители', 'proizvoditeli');
?>

<section id="main">
    <div class="wrap">
        <aside>
            <?= LeftCatalogWidget::widget() ?>
        </aside>
        <div id="content" class="container">
            <?= SearchBlockWidget::widget(); ?>

            <div class="breadcrumb">
                <?= yii\widgets\Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'encodeLabels' => false,
                    'options' => [
                        'class' => 'nav'
                    ],
                ]) ?>
            </div>

            <div class="page text-left">
                <header>
                    <h1>
                        Производители
                    </h1>
                </header>
                <div class="alphabet">
                    <?php foreach($enAlphabet as $alph) { ?>
                        <?php if(isset($manufacters[$alph]) && !empty($manufacters[$alph])) { ?>
                            <a href="#<?=$alph?>"><?=$alph?></a>
                        <?php } else { ?>
                            <?=$alph?>
                        <?php } ?>
                    <?php } ?>
                </div>
                <div class="alphabet">
                    <?php foreach($ruAlphabet as $alph) { ?>
                        <?php if(isset($manufacters[$alph]) && !empty($manufacters[$alph])) { ?>
                            <a href="#<?=$alph?>"><?=$alph?></a>
                        <?php } else { ?>
                            <?=$alph?>
                        <?php } ?>
                    <?php } ?>
                </div>
                <div class="manufacters">
                    <?php foreach($manufacters as $k=>$manufacter) { ?>
                        <header>
                            <span id="<?=$k?>"><?=$k?></span>
                        </header>
                        <div>
                            <?php foreach($manufacter as $mn) { ?>
                                <?= Html::a($mn['mn_name'], ['site/show', 'name' => $mn['mn_url']]) ?>&nbsp;
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>